# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Oh sorry Iamfrench
tagline:          'Ohsorryiamfrench'
description:      'Blog of Alexandre Page. Programming-related posts. Ruby, Swift ❤️'
url:              https://pagealexandre.github.io
#baseurl:          /algoliasearch-jekyll-hyde
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:           
  name:           Alexandre Page
  email:          
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/algolia/algoliasearch-jekyll-hyde

# Algolia
plugins:

algolia:
  application_id: '89UJC37P4L'
  index_name: 'jekyll_posts_production'
  read_only_api_key: '6830f27e0743dd352d36fcff666532ae'
  excluded_files:
    - 404.html
    - index.html
    - about.md
