# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Oh sorry Iamfrench
tagline:          'Ohsorryiamfrench'
description:      'My daily adventures as software engineer'
url:              https://pagealexandre.github.io
#baseurl:          /algoliasearch-jekyll-hyde
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:           
  name:           Alexandre Page
  email:          page_a@Ohsorryiamfrench.fr
# Thanks to @mdo for the original theme
# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/algolia/algoliasearch-jekyll-hyde

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'PYPITZ0454'
  index_name: 'post_jekyll'
  read_only_api_key: '5aac81c47674be30de1505a6c75f3a5f'
  excluded_files:
    - 404.html
    - index.html
    - about.md
